backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Landing Title, name: title, widget: string}
          - {label: Landing Image, name: image, widget: image}
          - {label: Landing Heading, name: heading, widget: text}
          - {label: Landing Subheading, name: subheading, widget: text}
          - {label: Landing Mainpitch, name: mainpitch, widget: object, fields: [{label: Landing Mainpitch Title, name: title, widget: string}, {label: Landing Mainpitch Description, name: description, widget: text}]}
          - {label: Landing Description, name: description, widget: text}
          - {label: Landing Intro, name: intro, widget: object, fields: [{label: Landing Intro Heading, name: heading, widget: string}, {label: Landing Intro Description, name: description, widget: text}, {label: Landing Intro Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Landing Main, name: main, widget: object, fields: [{label: Landing Main Heading, name: heading, widget: string}, {label: Landing Main Description, name: description, widget: text}, {label: Landing Main Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Landing Main Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Landing Main Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "About Title", name: "title", widget: "string"}
          - {label: "About Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Prod Title, name: title, widget: string}
          - {label: Prod Image, name: image, widget: image}
          - {label: Prod Heading, name: heading, widget: string}
          - {label: Prod Description, name: description, widget: string}
          - {label: Prod Intro Heaing, name: intro, widget: object, fields: [{label: Intro Heading, name: heading, widget: string}, {label: Prod Intro Description, name: description, widget: text}, {label: Prod Intro Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Prod Main, name: main, widget: object, fields: [{label: Main Heading, name: heading, widget: string}, {label: Prod Main Description, name: description, widget: text}, {label: Prod Main Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Prod Main Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Prod Main Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Prod Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Prod Full_image, name: full_image, widget: image}
          - {label: Prod Pricing, name: pricing, widget: object, fields: [{label: Pricing Heading, name: heading, widget: string}, {label: Pricing Description, name: description, widget: string}, {label: Pricing Plans, name: plans, widget: list, fields: [{label: Pricing Plan, name: plan, widget: string}, {label: Pricing Price, name: price, widget: string}, {label: Pricing Price Description, name: description, widget: string}, {label: Pricing Price Items, name: items, widget: list}]}]}
